import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: "#F8F9FA" },
  listContent: { paddingBottom: 20,paddingTop: 16 },
  header: {
    backgroundColor: "white",
    padding: 16,
    marginBottom: 16,
    borderRadius: 12,
    marginHorizontal: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  headerTop: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  headerTitle: { fontSize: 24, fontWeight: "bold", color: "#2C3E50" },
  clearAllButton: { color: "#FF3B30", fontSize: 16, fontWeight: "600" },
  headerSubtitle: { fontSize: 16, color: "#666" },
  cartItem: {
    backgroundColor: "white",
    flexDirection: "row",
    padding: 16,
    marginHorizontal: 16,
    marginBottom: 12,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  productImage: {
    width: 80,
    height: 80,
    borderRadius: 8,
    backgroundColor: "#F8F9FA",
  },
  itemDetails: { flex: 1, marginLeft: 12 },
  productTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: "#2C3E50",
    marginBottom: 4,
  },
  productPrice: {
    fontSize: 14,
    color: "#007AFF",
    fontWeight: "600",
    marginBottom: 2,
  },
  productCategory: { fontSize: 12, color: "#999" },
  quantityControls: { alignItems: "center", justifyContent: "space-between" },
  quantityContainer: {
    flexDirection: "row",
    borderWidth: 1,
    borderColor: "#E5E5EA",
    borderRadius: 6,
    marginBottom: 8,
  },
  quantityButton: {
    width: 32,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#F8F9FA",
  },
  quantityButtonLeft: { borderTopLeftRadius: 5, borderBottomLeftRadius: 5 },
  quantityButtonRight: { borderTopRightRadius: 5, borderBottomRightRadius: 5 },
  quantityDisplay: {
    width: 40,
    height: 32,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "white",
  },
  quantityText: { fontSize: 16, fontWeight: "600", color: "#2C3E50" },
  itemTotal: {
    fontSize: 16,
    fontWeight: "bold",
    color: "#2C3E50",
    marginBottom: 8,
  },
  removeButton: { padding: 4 },
  footer: {
    backgroundColor: "white",
    margin: 16,
    borderRadius: 12,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  totalContainer: { marginBottom: 16 },
  totalRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  totalLabel: { fontSize: 16, color: "#666" },
  totalValue: { fontSize: 16, color: "#2C3E50", fontWeight: "500" },
  freeShipping: { fontSize: 16, color: "#34C759", fontWeight: "600" },
  grandTotalRow: {
    borderTopWidth: 1,
    borderTopColor: "#E5E5EA",
    paddingTop: 12,
    marginTop: 8,
    marginBottom: 0,
  },
  grandTotalLabel: { fontSize: 18, fontWeight: "bold", color: "#2C3E50" },
  grandTotalValue: { fontSize: 18, fontWeight: "bold", color: "#007AFF" },
  checkoutButton: {
    backgroundColor: "#007AFF",
    paddingVertical: 16,
    borderRadius: 8,
    alignItems: "center",
  },
  checkoutButtonText: { color: "white", fontSize: 18, fontWeight: "bold" },
  emptyContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingHorizontal: 40,
  },
  emptyTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#2C3E50",
    marginTop: 24,
    textAlign: "center",
  },
  emptySubtitle: {
    fontSize: 16,
    color: "#666",
    marginTop: 12,
    textAlign: "center",
    lineHeight: 24,
  },
  shopNowButton: {
    backgroundColor: "#007AFF",
    paddingHorizontal: 32,
    paddingVertical: 12,
    borderRadius: 8,
    marginTop: 32,
  },
  shopNowButtonText: { color: "white", fontSize: 16, fontWeight: "600" },
});
