import { Product } from "../types";

export const mockProducts: Product[] = [
  {
    id: "1",
    title: "iPhone 15 Pro",
    price: 999.99,
    description:
      "The most advanced iPhone with A17 Pro chip and titanium design",
    category: "Electronics",
    image:
      "https://via.placeholder.com/200x200/007AFF/FFFFFF?text=iPhone+15+Pro",
  },
  {
    id: "2",
    title: "MacBook Air M2",
    price: 1299.99,
    description: "Supercharged by M2 chip, incredibly thin and light laptop",
    category: "Electronics",
    image: "https://via.placeholder.com/200x200/34C759/FFFFFF?text=MacBook+Air",
  },
  {
    id: "3",
    title: "AirPods Pro",
    price: 249.99,
    description: "Active Noise Cancellation and Adaptive Transparency",
    category: "Electronics",
    image: "https://via.placeholder.com/200x200/FF9500/FFFFFF?text=AirPods+Pro",
  },
  {
    id: "4",
    title: 'iPad Pro 12.9"',
    price: 1099.99,
    description: "The ultimate iPad experience with M2 chip",
    category: "Electronics",
    image: "https://via.placeholder.com/200x200/5856D6/FFFFFF?text=iPad+Pro",
  },
  {
    id: "5",
    title: "Apple Watch Series 9",
    price: 399.99,
    description: "Your essential companion with advanced health features",
    category: "Wearables",
    image: "https://via.placeholder.com/200x200/FF2D92/FFFFFF?text=Apple+Watch",
  },
  {
    id: "6",
    title: "Gaming Mouse",
    price: 79.99,
    description: "High-precision wireless gaming mouse with RGB lighting",
    category: "Accessories",
    image:
      "https://via.placeholder.com/200x200/8E8E93/FFFFFF?text=Gaming+Mouse",
  },
  {
    id: "7",
    title: "Wireless Keyboard",
    price: 129.99,
    description: "Mechanical wireless keyboard with backlight",
    category: "Accessories",
    image: "https://via.placeholder.com/200x200/30D158/FFFFFF?text=Keyboard",
  },
  {
    id: "8",
    title: "4K Monitor",
    price: 599.99,
    description: "27-inch 4K UHD monitor with HDR support",
    category: "Electronics",
    image: "https://via.placeholder.com/200x200/007AFF/FFFFFF?text=4K+Monitor",
  },
  {
    id: "9",
    title: "USB-C Hub",
    price: 89.99,
    description: "7-in-1 USB-C hub with HDMI, USB 3.0, and SD card reader",
    category: "Accessories",
    image: "https://via.placeholder.com/200x200/FF3B30/FFFFFF?text=USB-C+Hub",
  },
  {
    id: "10",
    title: "Bluetooth Speaker",
    price: 199.99,
    description: "Portable waterproof Bluetooth speaker with premium sound",
    category: "Audio",
    image: "https://via.placeholder.com/200x200/32D74B/FFFFFF?text=Speaker",
  },
  {
    id: "11",
    title: "Wireless Charger",
    price: 49.99,
    description: "Fast wireless charging pad compatible with all devices",
    category: "Accessories",
    image: "https://via.placeholder.com/200x200/5AC8FA/FFFFFF?text=Charger",
  },
  {
    id: "12",
    title: "Laptop Stand",
    price: 59.99,
    description: "Adjustable aluminum laptop stand for better ergonomics",
    category: "Accessories",
    image: "https://via.placeholder.com/200x200/FFCC02/FFFFFF?text=Stand",
  },
];
